version: "3.8"

services:
  web:
    build:
      context: ./flask-docker
      dockerfile: Dockerfile
    environment:
      FLASK_APP: manage
      FLASK_DEBUG: 1
    volumes:
      - ./flask-docker:/app
    command: flask run -h 0.0.0.0
    depends_on:
      - redis
    ports:
      - 5000:5000
    restart: always
  
  redis:
    image: redis:7.2
    ports:
      - 6380:6380
    restart: always

  celery-worker:
    build:
      context: ./flask-docker
    volumes:
      - ./flask-docker:/app
    environment:
      FLASK_APP: run
    command: celery -A manage.celery worker -B --loglevel=info
    depends_on:
      - redis
    restart: always

  flower:
    build:
      context: ./flask-docker
    volumes:
      - ./flask-docker:/app
    environment:
      FLASK_APP: run
    command: celery -A manage.celery flower --port=5555
    depends_on:
      - redis
      - celery-worker
    ports:
      - "5555:5555"
    restart: always